# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: pygments
markdown: kramdown
disqus: Maximuum
google_analytics: Maximuum

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: Maximuum

description: 
author:
  name: Maximuum
  email: Maximuum@163.com
  github: MaxIsComing
  twitter: 
  pinterest: 
  linkedin: 
  bio: 学习React-Native喜欢Nodejs纯服务器开发的iOS程序猿
  email_md5: 

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

BASE_PATH:
